# Generated by Django 5.2.15 on 2026-06-13 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.UniqueConstraint(fields=('expense', 'member'), name='unique_expense_split_member'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='expense_split_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.UniqueConstraint(fields=('trip', 'from_member', 'to_member', 'amount'), name='unique_settlement_suggestion'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tripmember',
            constraint=models.UniqueConstraint(fields=('trip', 'display_name'), name='unique_trip_member_display_name'),
        ),
        migrations.AddConstraint(
            model_name='tripmember',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('trip', 'user'), name='unique_trip_member_user'),
        ),
    ]
